services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - '443:443'
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www
    networks:
      - inception-net
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress-volume:/var/www
    networks:
      - inception-net
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_PASS: ${MYSQL_PASSWORD}
        DB_USER: ${MYSQL_USER}
        DB_ROOT: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-net

networks:
  inception-net:
    driver: bridge

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb
