services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - '443:443'
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-net
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-net
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-net

networks:
  inception-net:
    driver: bridge
volumes:
  wordpress:
  mariadb: